#pragma once
#include "../../main.h"

#include "RoleControlBase.h"
#include "../Animator/AnimatorControl.h"

struct RoleControl : RoleControlBase {
	AnimatorControl* animatorControl;
	char xiaoChangChangAnim[0x000004];
	float h_moveDir;
	float v_moveDir;
	float y_camRot;
	float x_camRot;
	UnityResolve::UnityType::Transform* BodyY;
	UnityResolve::UnityType::Transform* Body;
	UnityResolve::UnityType::Transform* HandIKTarget;
	UnityResolve::UnityType::Transform* PoleTarget;
	char _mySOGameSetting[0x000004];
	char myHitType[0x000004];
	std::int64_t animPlayerId;
	bool isClearAnimToPool;
	char isClearAnimToPool_[0x000003];
	float delayResetCarAniStateTime;
	float currentDelayResetCarAniStateTime;
	float delayTime;
	char isShowXiaoChangChang[0x000004];
	UnityResolve::UnityType::Vector3 ikTargetPoint;
	UnityResolve::UnityType::Vector3 poleTagetPoint;
	bool isPlayColliderSizeAnim;
	char isPlayColliderSizeAnim_[0x000003];
	float driveHAccel;
	float driveHDamping;
	float driveHAmount;
	float flyVertical;
	float flyHorizontal;
	float flyAccelNormalizedVertical;
	float flyAccelNormalizedHorizontal;
	float flyDampingNormalized;
	float flyAngleX;
	float flySpeedDown;
	float flySpeedForward;
	UnityResolve::UnityType::Vector3 flySpeedLocal;
	UnityResolve::UnityType::Vector3 HookFlyToward;
	bool lastStatus;
	bool IsFlyEntered;
	bool isOpenParachute;
	bool isSendFlyHigh;
	UnityResolve::UnityType::Vector3 headPoint;
	bool preIsHoldOn;
	bool preIsDraw;
	char preIsDraw_[0x000002];
	UnityResolve::UnityType::GameObject* paoKuRoll;
	char paokuRollState[0x000004];
	UnityResolve::UnityType::GameObject* snowMan;
	char snowManState[0x000004];
	char appendObMatObMat[0x000004];
};